spring.application.name=config-server

server.port=8888

# GitHub Config Repository
spring.cloud.config.server.git.uri=https://github.com/VISHAL55UIET/ecommerce-microservices

# Public Repository
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main