spring.application.name=api-gateway

server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =========================
# Order Service
# =========================
spring.cloud.gateway.server.webmvc.routes[0].id=order-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/orders/**

# =========================
# Inventory Service
# =========================
spring.cloud.gateway.server.webmvc.routes[1].id=inventory-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/**