spring.application.name=api-gateway

server.port=8080

# ============================
# Eureka
# ============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
# ============================
# Gateway Routes
# ============================
spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/orders/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=LoggingOrdersFilter

spring.cloud.gateway.server.webflux.routes[1].id=inventory-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/**

# ============================
# Micrometer + Zipkin
# ============================
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always